[CmdletBinding()]
param([switch]$AuthorizeSingleUnrealProof,[switch]$OfflineContractTest,[string]$OfflineEvidenceRoot)
Set-StrictMode -Version Latest;$ErrorActionPreference='Stop'
$source='D:\Skyguard52\Scripts\ToolchainWave08\m01_polyhaven_vegetation_staging02_visual_proof01\invoke_m01_polyhaven_vegetation_staging02_visual_proof01_once.ps1';$expectedBytes=3410;$expectedSha256='31f0ab182d5334029b44d8c6a07cc9f5af9d44ec500fe3154f6200742d421523'
function Get-LowerSha256([string]$Path){$s=$null;$a=$null;try{$s=[IO.File]::Open($Path,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);$a=[Security.Cryptography.SHA256]::Create();return([BitConverter]::ToString($a.ComputeHash($s))).Replace('-','').ToLowerInvariant()}finally{if($null-ne $a){$a.Dispose()};if($null-ne $s){$s.Dispose()}}}
if(-not(Test-Path -LiteralPath $source -PathType Leaf)){throw "Missing frozen Stage02 supervisor"};$i=Get-Item $source;if($i.Length-ne $expectedBytes-or(Get-LowerSha256 $source)-ne $expectedSha256){throw 'Frozen Stage02 supervisor changed'}
# Invoke in a child scope. The child still writes the global transformed source,
# but its OfflineContractTest parameter cannot leak into this Recovery05 scope.
try{& $source -OfflineContractTest -OfflineEvidenceRoot $OfflineEvidenceRoot}catch{}
$transformed=$global:SkyguardTransformedSupervisorSource;if([string]::IsNullOrWhiteSpace($transformed)){throw 'Transformed base unavailable'}
$pairs=@(@('PASSED_READY_FOR_STANDING_AUTHORIZED_SINGLE_M01_POLYHAVEN_VEGETATION_STAGING02_VISUAL_PROOF01_EXECUTION','__READY__'),@('M01_POLYHAVEN_VEGETATION_STAGING02_VISUAL_PROOF01','__UPPER__'),@('M01-POLYHAVEN-VEGETATION-STAGING02-VISUAL-PROOF01','__KEBAB__'),@('M01PolyHavenVegetationStaging02VisualProof01.csv','__CSV__'),@('m01_polyhaven_vegetation_staging02_visual_proof01','__LOWER__'),@('polyhaven-vegetation-staging02-visual-proof01','__LOWER_KEBAB__'))
foreach($p in $pairs){if(-not $transformed.Contains($p[0])){throw "Missing Recovery05 token: $($p[0])"};$transformed=$transformed.Replace($p[0],$p[1])}
$pairs=@(@('__READY__','PASSED_READY_FOR_STANDING_AUTHORIZED_SINGLE_M01_POLYHAVEN_VEGETATION_STAGING02_VISUAL_PROOF01_RECOVERY05_EXECUTION'),@('__UPPER__','M01_POLYHAVEN_VEGETATION_STAGING02_VISUAL_PROOF01_RECOVERY05'),@('__KEBAB__','M01-POLYHAVEN-VEGETATION-STAGING02-VISUAL-PROOF01-RECOVERY05'),@('__CSV__','M01PolyHavenVegetationStaging02VisualProof01Recovery05.csv'),@('__LOWER__','m01_polyhaven_vegetation_staging02_visual_proof01_recovery05'),@('__LOWER_KEBAB__','polyhaven-vegetation-staging02-visual-proof01-recovery05'))
foreach($p in $pairs){$transformed=$transformed.Replace($p[0],$p[1])};if($transformed.Contains('RECOVERY05_RECOVERY05')-or$transformed.Contains('recovery05_recovery05')){throw 'Duplicate Recovery05 suffix'};if([regex]::Matches($transformed,[regex]::Escape('Start-Process -FilePath $editor')).Count-ne 1){throw 'Wrong launch count'}
$block=[ScriptBlock]::Create($transformed);$args=@{};if($AuthorizeSingleUnrealProof){$args['AuthorizeSingleUnrealProof']=$true};if($OfflineContractTest){$args['OfflineContractTest']=$true;if($OfflineEvidenceRoot){$args['OfflineEvidenceRoot']=$OfflineEvidenceRoot}};& $block @args
